/**
 * Hotel Data Builder Script
 *
 * This script parses hotel data from the AwardTravel list and enriches it with coordinates.
 * Run with: npx tsx tools/build-hotel-data.ts
 */

import { writeFileSync, readFileSync, existsSync } from 'fs';
import { v4 as uuidv4 } from 'uuid';
import type { Hotel, HotelDataset } from '../lib/types';

// Raw hotel entries parsed from AwardTravel (name - location format)
const rawHotels: string[] = [
  // Anguilla
  "Aurora Anguilla Resort & Golf Club - Rendezvous Bay, Anguilla",
  "Cap Juluca, A Belmond Hotel - Maundays Bay, Anguilla",
  "Four Seasons Resort and Residences Anguilla - West End Village, Anguilla",
  "Malliouhana Resort Anguilla - West End Village, Anguilla",
  // Antigua & Barbuda
  "Carlisle Bay - Saint Mary Parish, Antigua & Barbuda",
  "Jumby Bay Island, Oetker Hotels - St. John's, Antigua & Barbuda",
  "The Inn at English Harbour - St. Paul's, Antigua & Barbuda",
  // Argentina
  "Faena Hotel Buenos Aires - Buenos Aires, Argentina",
  "Four Seasons Hotel Buenos Aires - Buenos Aires, Argentina",
  "Palacio Duhau - Park Hyatt Buenos Aires - Buenos Aires, Argentina",
  "The Vines Resort & Spa - Tunuyan - Uco Valley - Mendoza, Argentina",
  // Aruba
  "Hyatt Regency Aruba Resort Spa & Casino - Palm Beach, Aruba",
  "The Ritz-Carlton, Aruba - Aruba",
  // Australia
  "COMO The Treasury - Perth, Australia",
  "Four Seasons Hotel Sydney - Sydney, Australia",
  "InterContinental Sydney by IHG - Sydney, Australia",
  "Kimpton Margot Sydney by IHG - Sydney, Australia",
  "Mount Lofty House & Estate Adelaide Hills - Crafers, Australia",
  "Shangri-La Sydney - The Rocks, Australia",
  "Shangri-La The Marina, Cairns - Cairns, Australia",
  "Sofitel Melbourne On Collins - Melbourne, Australia",
  "The Langham, Melbourne - Melbourne, Australia",
  "The Langham, Sydney - Sydney, Australia",
  "The Ritz-Carlton, Perth - Perth, Australia",
  "W Brisbane - Brisbane, Australia",
  "W Melbourne - Melbourne, VIC, Australia",
  // Austria
  "Almanac Palais Vienna - Wien, Austria",
  "Anantara Palais Hansen Vienna Hotel - Vienna, Austria",
  "Hotel Goldener Hirsch, a Luxury Collection Hotel, Salzburg - Salzburg, Austria",
  "Hotel Imperial, a Luxury Collection Hotel, Vienna - Vienna, Austria",
  "Hotel Sacher Wien - Vienna, Austria",
  "SO/ Vienna - Vienna, Austria",
  "The Amauris Vienna - Relais & Châteaux - Vienna, Austria",
  "The Ritz-Carlton, Vienna - Vienna, Austria",
  "Thurnher's Alpenhof - Zuers am Arlberg, Austria",
  // Azerbaijan
  "Four Seasons Hotel Baku - Baku, Azerbaijan",
  // Bahamas
  "Pink Sands Resort - Dunmore Town, Bahamas",
  "SLS Baha Mar - Nassau, Bahamas",
  "The Cove at Atlantis - Paradise Island, Bahamas",
  "The Ocean Club, Bahamas - A Four Seasons Resort - Paradise Island, Bahamas",
  "The Reef at Atlantis - Paradise Island, Bahamas",
  // Bahrain
  "Four Seasons Hotel Bahrain Bay - Manama, Bahrain",
  // Barbados
  "Fairmont Royal Pavilion - St. James, Barbados",
  // Belgium
  "Corinthia Grand Hotel Astoria, Brussels - Brussels, Belgium",
  "Le Louise Hotel Brussels - MGallery - Brussels, Belgium",
  "Rocco Forte Hotel Amigo - Brussels, Belgium",
  "Sofitel Brussels Europe - Brussels, Belgium",
  // Belize
  "Alaia Belize, Autograph Collection - San Pedro Ambergris Caye, Belize",
  "Itz'ana Resort & Residences, Placencia - Placencia, Belize",
  // Bermuda
  "Hamilton Princess & Beach Club - a Fairmont Managed Hotel - Pembroke Parish, Bermuda",
  "The Loren at Pink Beach - Tuckers Town, Bermuda",
  // Botswana
  "Belmond Safaris - Maun, Botswana",
  "Xigera Safari Lodge - Maun, Botswana",
  // Brazil
  "Copacabana Palace, A Belmond Hotel, Rio de Janeiro - Rio de Janeiro, Brazil",
  "Fairmont Rio de Janeiro Copacabana - Rio de Janeiro, Brazil",
  "Hotel das Cataratas, A Belmond Hotel, Iguassu Falls - Foz do Iguaçu, Brazil",
  "InterContinental São Paulo by IHG - São Paulo, Brazil",
  "Palácio Tangará - an Oetker Collection Hotel - São Paulo, Brazil",
  "Santa Teresa Hotel Rio de Janeiro - MGallery Collection - Rio de Janeiro, Brazil",
  // Cambodia
  "Raffles Grand Hotel d'Angkor - Siem Reap, Cambodia",
  "Six Senses Krabey Island - Prey Nob, Cambodia",
  // Canada
  "1 Hotel Toronto - Toronto, Canada",
  "Auberge Saint-Antoine - Québec city, Canada",
  "Fairmont Banff Springs - Banff, Canada",
  "Fairmont Chateau Lake Louise - Lake Louise, Canada",
  "Fairmont Chateau Laurier - Ottawa, Canada",
  "Fairmont Chateau Whistler - Whistler, Canada",
  "Fairmont Hotel Vancouver - Vancouver, Canada",
  "Fairmont Jasper Park Lodge - Jasper, Canada",
  "Fairmont Le Chateau Frontenac - Québec City, Canada",
  "Fairmont Pacific Rim - Vancouver, Canada",
  "Fairmont The Queen Elizabeth - Montreal, Canada",
  "Fairmont Waterfront - Vancouver, Canada",
  "Fogo Island Inn - Joe Batt's Arm, Canada",
  "Four Seasons Hotel Montreal - Montreal, Canada",
  "Four Seasons Hotel Toronto - Toronto, Canada",
  "Four Seasons Resort Whistler - Whistler, Canada",
  "Muir, a Luxury Collection Hotel, Halifax - Halifax, Canada",
  "Park Hyatt Toronto - Toronto, Canada",
  "Shangri-La Vancouver - Vancouver, Canada",
  "Shangri-La, Toronto - Toronto, Canada",
  "Sofitel Montreal Golden Mile - Montreal, Canada",
  "The Ritz-Carlton, Montreal - Montreal, Canada",
  "The Ritz-Carlton, Toronto - Toronto, Canada",
  "The St. Regis Toronto - Toronto, Canada",
  "Vogue Hotel Montreal Downtown, Curio Collection by Hilton - Montreal, Canada",
  "W Toronto - Toronto, Canada",
  // Cayman Islands
  "Hotel Indigo Grand Cayman - Cayman Islands",
  "Kimpton Seafire Resort + Spa by IHG - Seven Mile Beach, Cayman Islands",
  "The Ritz-Carlton, Grand Cayman - Grand Cayman, Cayman Islands",
  // Chile
  "The Ritz-Carlton, Santiago - Santiago, Chile",
  // China
  "Bulgari Hotel Beijing - Beijing, China",
  "Bulgari Hotel Shanghai - Shanghai, China",
  "Four Seasons Hotel Beijing - Beijing, China",
  "Four Seasons Hotel Hangzhou At Hangzhou Centre - Hangzhou, China",
  "Four Seasons Hotel Hangzhou at West Lake - Hangzhou, China",
  "Four Seasons Hotel Shenzhen - Shenzhen, China",
  "Four Seasons Hotel Suzhou - Suzhou, China",
  "Four Seasons Hotel Tianjin - Tianjin, China",
  "Intercontinental Xiangyang by IHG - Xiangyang, China",
  "Kimpton Qiantan Shanghai by IHG - Shanghai, China",
  "Rissai Valley, a Ritz-Carlton Reserve - Jiuzhaigou, China",
  "The Langham, Shenzhen - Shenzhen, China",
  "The Middle House - Shanghai, China",
  "The Peninsula Beijing - Beijing, China",
  "The Peninsula Shanghai - Shanghai, China",
  "The Shanghai EDITION - Shanghai, China",
  // Colombia
  "Casa Pestagua Relais Châteaux - Cartagena, Colombia",
  "Four Seasons Hotel Bogota - Bogotá, Colombia",
  "Four Seasons Hotel Casa Medina, Bogotá - Bogota, Colombia",
  "InterContinental Cartagena De Indias by IHG - Cartagena, Colombia",
  "Sofitel Barú Cartagena Beach Resort - Cartagena de Indias, Colombia",
  "Sofitel Legend Santa Clara Cartagena - Cartagena, Colombia",
  // Costa Rica
  "Four Seasons Resort Peninsula Papagayo, Costa Rica - Nacascolo, Costa Rica",
  "Hotel Nantipa - A Tico Beach Experience - Cóbano, Costa Rica",
  "Los Altos Resort - Manuel Antonio, Costa Rica",
  "Nayara Gardens - La Fortuna, Costa Rica",
  "Nayara Springs - Adults only - La Fortuna, Costa Rica",
  "Nayara Tented Camp - La Fortuna, Costa Rica",
  "Nekajui, a Ritz-Carlton Reserve - Nacascolo, Costa Rica",
  "Tabacon Thermal Resort & Spa - Arenal, Costa Rica",
  "W Costa Rica - Reserva Conchal - Cabo Velas, Costa Rica",
  // Croatia
  "Grand Hotel Brioni Pula, A Radisson Collection Hotel - Pula, Croatia",
  "Kempinski Hotel Adriatic - Savudrija, Croatia",
  "Maslina Resort - Stari Grad, Croatia",
  "Radisson Blu Resort & Spa, Split - Split, Croatia",
  "Sun Gardens Dubrovnik - Dubrovnik, Croatia",
  "Villa Dubrovnik - Dubrovnik, Croatia",
  // Cyprus
  "Parklane, a Luxury Collection Resort & Spa, Limassol - Limassol, Cyprus",
  // Czechia
  "Andaz Prague - Prague, Czechia",
  "Augustine, a Luxury Collection Hotel, Prague - Prague, Czechia",
  "Four Seasons Hotel Prague - Prague, Czechia",
  // Denmark
  "NH Collection Copenhagen - Copenhagen, Denmark",
  "Nimb Hotel - Copenhagen, Denmark",
  "Nobis Hotel Copenhagen, a Member of Design Hotels - Copenhagen, Denmark",
  // Dominica
  "Intercontinental Dominica Cabrits Resort & Spa - Portsmouth, Dominica",
  // Dominican Republic
  "Casa de Campo Resort & Villas - La Romana, Dominican Republic",
  "Eden Roc Cap Cana - Cap Cana, Dominican Republic",
  "Kimpton Las Mercedes by IHG - Santo Domingo, Dominican Republic",
  "Paradisus Palma Real Golf & Spa Resort All Inclusive - Punta Cana, Dominican Republic",
  "The St Regis Cap Cana Resort - Punta Cana, Dominican Republic",
  "Tortuga Bay Puntacana Resort & Club - Punta Cana, Dominican Republic",
  // Egypt
  "Four Seasons Hotel Alexandria at San Stefano - Alexandria, Egypt",
  "Four Seasons Hotel Cairo at Nile Plaza - Cairo, Egypt",
  "Four Seasons Hotel Cairo at The First Residence - Cairo, Egypt",
  "Four Seasons Resort Sharm EL Sheikh - Sharm El Sheikh, Egypt",
  // Fiji
  "Nanuku Resort, Fiji - Pacific Harbour, Fiji",
  "Six Senses Fiji - Malolo Island, Fiji",
  "Sofitel Fiji Resort & Spa Denarau Island - Nadi, Fiji",
  // Finland
  "Hotel NH Collection Helsinki Grand Hansa - Helsinki, Finland",
  "The Hotel Maria - Helsinki, Finland",
  // France
  "Anantara Plaza Nice Hotel - Nice, France",
  "Bulgari Hotel Paris - Paris, France",
  "Carlton Cannes, a Regent Hotel - Cannes, France",
  "Castille Paris – Starhotels Collezione - Paris, France",
  "Château De Berne - Flayosc, France",
  "Chateau De Fonscolombe - Le Puy-Sainte-Réparade, France",
  "Cheval Blanc Paris - Paris, France",
  "COMO Le Montrachet - Puligny-Montrachet, France",
  "Coquillade Provence - Gargas, France",
  "Domaine de Primard - Guainville, France",
  "Five Seas by Inwood Hotels - Cannes, France",
  "Fleur de Loire - Blois, France",
  "Four Seasons Hotel George V - Paris, France",
  "Four Seasons Hotel Megeve - Megeve, France",
  "Grand-Hôtel du Cap-Ferrat, A Four Seasons Hotel - Saint-Jean-Cap-Ferrat, France",
  "Hotel Barriere Le Fouquets Paris - Paris, France",
  "Hotel Barriere Le Majestic Cannes - Cannes, France",
  "Hôtel Plaza Athénée - Dorchester Collection - Paris, France",
  "InterContinental Bordeaux - Le Grand Hotel - Bordeaux, France",
  "InterContinental Chantilly Chateau Mont Royal by IHG - La Chapelle-en-Serval, France",
  "InterContinental Lyon - Hotel Dieu - Lyon, France",
  "InterContinental Marseille - Hotel Dieu by IHG - Marseille, France",
  "InterContinental Paris le Grand by IHG - Paris, France",
  "J.K. Place Paris - Paris, France",
  "JW Marriott Cannes - Cannes, France",
  "Kimpton St Honore Paris by IHG - Paris, France",
  "La Fantaisie - Paris, France",
  "La Mirande - Avignon, France",
  "La Reserve Paris- Hotel and Spa - Paris, France",
  "Le Bristol Paris, Oetker Hotels - Paris, France",
  "Le Meurice - Dorchester Collection - Paris, France",
  "Le Royal Monceau - Raffles Paris - Paris, France",
  "Lutetia Hotel - Paris, France",
  "Maison Delano Paris - Paris, France",
  "Mondrian Bordeaux Les Carmes - Bordeaux, France",
  "Mondrian Cannes - Cannes, France",
  "Park Hyatt Paris Vendome - Paris, France",
  "Pavillon Faubourg Saint-Germain - Paris, France",
  "Relais Christine - Paris, France",
  "Ritz Paris - Paris, France",
  "Saint James Paris - Paris, France",
  "Shangri-La Paris - Paris, France",
  "SO/ Paris - Paris, France",
  "Sofitel Paris Baltimore Tour Eiffel Hotel - Paris, France",
  "Sofitel Paris Le Faubourg - Paris, France",
  "The Maybourne Riviera, Maybourne - Roquebrune-Cap-Martin, France",
  "The Peninsula Paris - Paris, France",
  "Villa Gallici Hôtel & Spa - Aix-en-Provence, France",
  // French Polynesia
  "Four Seasons Resort Bora Bora - Bora Bora, French Polynesia",
  "InterContinental Bora Bora Resort and Thalasso Spa by IHG - Bora Bora, French Polynesia",
  "Le Bora Bora - Bp 169, French Polynesia",
  "Le Taha'a - Tapuamu, French Polynesia",
  "Sofitel Kia Ora Moorea Beach Resort - Moorea-Maiao, French Polynesia",
  "The Brando - Tahiti, French Polynesia",
  "The St. Regis Bora Bora Resort - Bora Bora, French Polynesia",
  // Germany
  "Brenners Park-Hotel & Spa, Oetker Hotels - Baden-Baden, Germany",
  "Fairmont Hotel Vier Jahreszeiten Hamburg - Hamburg, Germany",
  "Kimpton Main Frankfurt by IHG - Frankfurt, Germany",
  "Rocco Forte Hotel De Rome Berlin - Berlin, Germany",
  "Rocco Forte The Charles Hotel - Munich, Germany",
  "SO/ Berlin Das Stue - Berlin, Germany",
  "Sofitel Frankfurt Opera - Frankfurt am Main, Germany",
  "Sofitel Munich Bayerpost - Munich, Germany",
  "The Ritz-Carlton, Berlin - Berlin, Germany",
  // Greece
  "Academias Hotel, Autograph Collection - Athens, Greece",
  "Amirandes, Grecotel Boutique Resort - Heraklion, Greece",
  "Andronis Minois - Paros Island, Greece",
  "Athenaeum InterContinental by IHG - Athens, Greece",
  "Athens Capital Center Hotel - Athens, Greece",
  "Bill & Coo Mykonos - Mykonos, Greece",
  "Canaves Epitome - Small Luxury Hotels of the World - Santorini, Greece",
  "Canaves Oia Suites - Santorini, Greece",
  "Caramel, Grecotel Boutique Resort - Rethymno, Crete, Greece",
  "Cosme, A Luxury Collection Resort, Paros - Paros, Greece",
  "Deos Mykonos - Mykonos, Greece",
  "Elounda Mare Hotel - Aghios Nikolaos, Greece",
  "Four Seasons Astir Palace Hotel Athens - Athens, Greece",
  "Hotel Grande Bretagne, a Luxury Collection Hotel, Athens - Athens, Greece",
  "InterContinental Crete by IHG - Agios Nikolaos, Greece",
  "Katikies Garden Santorini - Fira, Santorini, Greece",
  "Katikies Santorini - Santorini, Greece",
  "Kouros Hotel & Suites - Mykonos, Greece",
  "Magma Resort Santorini, part of The Unbound Collection by Hyatt - Santorini, Greece",
  "Minos Beach Art Hotel - Agios Nikolaos, Crete, Greece",
  "Myconian Ambassador Hotel Relais & Chateaux - Mykonos, Greece",
  "Myconian Villa Collection - Mykonos, Greece",
  "Mykonos Blu Boutique Resort - Mykonos, Greece",
  "Mykonos Grand Hotel & Resort - Mykonos, Greece",
  "Mystique, a Luxury Collection Hotel, Santorini - Santorini, Greece",
  "New Hotel - Athens, Greece",
  "Nobu Hotel Santorini - Santorini, Greece",
  "NOŪS Santorini - Santorini, Greece",
  "One&Only Aesthesis - Glyfada, Greece",
  "One&Only Kéa Island - Kea, Greece",
  "Parilio, a Member of Design Hotels - Paros, Greece",
  "Santo Pure Oia Suites & Villas - Oia, Santorini, Greece",
  "The Danai - Nikiti, Greece",
  "W Costa Navarino- Adults Only - Pylos-Nestoras, Greece",
  // Grenada
  "Calabash Hotel - St. George's, Grenada",
  "Six Senses La Sagesse Grenada - St. David, Grenada",
  // Honduras
  "Kimpton Grand Roatan Resort And Spa by IHG - Roatan, Honduras",
  // Hong Kong
  "Four Seasons Hotel Hong Kong - Hong Kong",
  "Island Shangri-La, Hong Kong - Hong Kong",
  "Kerry Hotel, Hong Kong - Kowloon, Hong Kong",
  "Mondrian Hong Kong - Hong Kong",
  "Regent Hong Kong - Kowloon, Hong Kong",
  "The Langham, Hong Kong - Kowloon, Hong Kong",
  "The Peninsula Hong Kong - Kowloon, Hong Kong",
  "The Upper House - Hong Kong",
  // Hungary
  "Al Habtoor Palace Budapest - Budapest, Hungary",
  "Corinthia Budapest - Budapest, Hungary",
  "Dorothea Hotel, Budapest, Autograph Collection - Budapest, Hungary",
  "Four Seasons Gresham Palace - Budapest, Hungary",
  "Kimpton BEM Budapest by IHG - Budapest, Hungary",
  // Iceland
  "The Reykjavik EDITION - Reykjavik, Iceland",
  // India
  "Four Seasons Hotel Bengaluru at Embassy One - Bengaluru, India",
  "Four Seasons Hotel Mumbai - Mumbai, India",
  "Raffles Jaipur - Jaipur, India",
  "Raffles Udaipur - Udaipur, India",
  "Six Senses Fort Barwara - Chauth Ka Barwara, India",
  "Six Senses Vana - A Wellness Retreat - Dehradun, India",
  "Taj Mahal, New Delhi - New Delhi, India",
  "The Leela Palace New Delhi - New Delhi, India",
  "The Oberoi Rajvilas, Jaipur - Jaipur, India",
  "The Oberoi Udaivilas - Udaipur, India",
  "The Oberoi, New Delhi - New Delhi, India",
  "The Ritz-Carlton, Bangalore - Bangalore, India",
  "The Taj Mahal Palace Mumbai - Mumbai, India",
  // Indonesia
  "Andaz Bali - Denpasar, Indonesia",
  "Bulgari Resort Bali - Uluwatu Bali, Indonesia",
  "COMO Shambhala Estate - Gianyar City, Indonesia",
  "COMO Uma Canggu - Canggu, Indonesia",
  "Four Seasons Hotel Jakarta - Jakarta, Indonesia",
  "Four Seasons Resort Bali at Jimbaran Bay - Jimbaran, Indonesia",
  "Four Seasons Resort Bali At Sayan - Bali, Indonesia",
  "Jumeirah Bali - Bali, Indonesia",
  "Mandapa, a Ritz-Carlton Reserve - Ubud, Bali, Indonesia",
  "NIHI Sumba - East Nusa Tenggara, Indonesia",
  "Raffles Bali - Jimbaran, Indonesia",
  "Regent Bali Canggu - Canggu, Indonesia",
  "Six Senses Uluwatu - Pecatu, Indonesia",
  "Soori Bali - Bali, Indonesia",
  "The Langham, Jakarta - Jakarta, Indonesia",
  // Ireland
  "Anantara The Marker Hotel Dublin Hotel - Dublin, Ireland",
  "Ashford Castle - Mayo, Ireland",
  "Carton House a Fairmont Managed Hotel - Maynooth, Ireland",
  "Dylan Hotel - Dublin, Ireland",
  "Glenlo Abbey Hotel - Galway, Ireland",
  "InterContinental Dublin by IHG - Dublin, Ireland",
  "Park Hotel Kenmare - Kenmare, Ireland",
  "The Fitzwilliam Hotel - Dublin, Ireland",
  "The Lodge at Ashford Castle - Cong, Co. Mayo, Ireland",
  "The Merrion Hotel - Dublin, Ireland",
  "The Shelbourne, Autograph Collection - Dublin, Ireland",
  "The Westbury Dublin - Dublin, Ireland",
  // Israel
  "InterContinental David Tel Aviv by IHG - Tel Aviv, Israel",
  "King David, Jerusalem - Jerusalem, Israel",
  "Mamilla Hotel - Jerusalem, Israel",
  "The David Citadel Jerusalem - Jerusalem, Israel",
  "The Jaffa, a Luxury Collection Hotel, Tel Aviv - Tel Aviv-Jaffa, Israel",
  // Italy
  "7Pines Resort Sardinia - Baja Sardinia, Italy",
  "Anantara Grand Hotel Convento di Amalfi Grand Hotel - Amalfi, Italy",
  "Baglioni Hotel Luna - Venice, Italy",
  "Baglioni Hotel Regina - Roma, Italy",
  "Borgo Egnazia - Fasano, Italy",
  "Bulgari Hotel Milano - Milan, Italy",
  "Bulgari Hotel Roma - Rome, Italy",
  "Ca' di Dio - Venice, Italy",
  "Cala di Volpe, a Luxury Collection Hotel, Costa Smeralda - Arzachena, Italy",
  "Caruso, A Belmond Hotel, Amalfi Coast - Ravello, Italy",
  "Casa Angelina - Praiano, Italy",
  "Casa Cipriani Milano - Milan, Italy",
  "Casa di Langa - Cerretto Langhe, Italy",
  "Castelfalfi - Montaione, Italy",
  "Castello Banfi - Il Borgo - Montalcino, Italy",
  "Castello di Casole, A Belmond Hotel, Tuscany - Siena, Italy",
  "COMO Castello Del Nero - Barberino Tavarnelle (Florence), Italy",
  "Four Seasons Hotel Firenze - Firenze, Italy",
  "Four Seasons Hotel Milano - Milan, Italy",
  "Gardena Grödnerhof Hotel & Spa - Castelrotto, Italy",
  "Grand Hotel et de Milan - Milan, Italy",
  "Grand Hotel Excelsior Vittoria - Sorrento, Italy",
  "Grand Hotel Savoia by Radisson Collection - Cortina d'Ampezzo, Italy",
  "Grand Hotel Timeo, A Belmond Hotel, Taormina - Taormina, Italy",
  "Grand Hotel Tremezzo, Lake Como - Tremezzina, Italy",
  "Grand Hotel Victoria Concept & Spa, by R Collection Hotels - Menaggio, Italy",
  "Helvetia & Bristol - Firenze, Italy",
  "Hotel Cipriani, A Belmond Hotel, Venice - Venice, Italy",
  "Hotel Eden - Dorchester Collection - Rome, Italy",
  "Hotel Le Fontanelle - Castelnuovo Berardenga (SI), Italy",
  "Hotel Lungarno - Florence, Italy",
  "Hotel Maalot Roma - Rome, Italy",
  "Hotel Principe Di Savoia - Milan, Italy",
  "Hotel Regency, Florence - Firenze, Italy",
  "Hotel Splendide Royal - Rome, Italy",
  "Hotel Terme di Saturnia Natural Spa & Golf Resort - Saturnia (GR), Italy",
  "Hotel Villa Franca Positano - Positano, Italy",
  "Il San Corrado di Noto Luxury Resort - Noto, Italy",
  "Il Sereno Lake Como - Torno, Italy",
  "InterContinental Rome Ambasciatori Palace - Roma, Italy",
  "J.K.Place Capri - Capri, Italy",
  "J.K.Place Roma - Rome, Italy",
  "Jumeirah Capri Palace - Anacapri, Italy",
  "La Roqqa - Porto Ercole, Italy",
  "Lefay Resort & SPA Dolomiti - Pinzolo, Italy",
  "Lefay Resort & SPA Lago Di Garda - Gargnano, Italy",
  "Londra Palace Venezia - Venice, Italy",
  "Mazzaro' Sea Palace - VRetreats - Taormina, Italy",
  "ME Milan il Duca - Milano, Italy",
  "Palazzo Ripetta - Rome, Italy",
  "Park Hyatt Milan - Milan, Italy",
  "Passalacqua - Moltrasio, Italy",
  "Pieve Aldina - Radda in Chianti, Italy",
  "Portrait Firenze - Florence, Italy",
  "Portrait Milano - Milan, Italy",
  "Portrait Roma - Lungarno Collection - Rome, Italy",
  "Radisson Collection Hotel, Palazzo Touring Club Milan - Milan, Italy",
  "Radisson Collection Palazzo Nani, Venice - Venice, Italy",
  "Rocco Forte Hotel de la Ville - Rome, Italy",
  "Rocco Forte Hotel De Russie - Rome, Italy",
  "Rocco Forte Hotel Savoy - Florence, Italy",
  "Rocco Forte Masseria Torre Maizza - Fasano, Italy",
  "Rocco Forte Private Villas - Sciacca, Italy",
  "Rocco Forte Villa Igiea - Palermo, Italy",
  "Romazzino, A Belmond Hotel, Costa Smeralda - Arzachena, Italy",
  "San Clemente Palace Kempinski, Venice - Venice, Italy",
  "San Domenico Palace, Taormina, A Four Seasons Hotel - Taormina, Italy",
  "Santa Caterina - Amalfi, Italy",
  "Sina Villa Medici, Autograph Collection - Florence, Italy",
  "Six Senses Rome - Rome, Italy",
  "Sofitel Rome Villa Borghese - Rome, Italy",
  "Splendido Mare, A Belmond Hotel, Portofino - Portofino, Italy",
  "Splendido, A Belmond Hotel, Portofino - Portofino, Italy",
  "Straf, Milan, a Member Of Design Hotels - Milan, Italy",
  "The Ashbee Hotel - Taormina, Italy",
  "The Gritti Palace, a Luxury Collection Hotel, Venice - Venice, Italy",
  "The Place Firenze - Florence, Italy",
  "The Rome EDITION - Roma, Italy",
  "The St. Regis Florence - Florence, Italy",
  "The St. Regis Rome - Rome, Italy",
  "The St. Regis Venice - Venice, Italy",
  "Verdura Resort - Sciacca, Italy",
  "Villa Agrippina a Gran Melia Hotel - Rome, Italy",
  "Villa Cora - Florence, Italy",
  "Villa d'Este - Cernobbio, Italy",
  "Villa La Massa - Bagno a Ripoli, Italy",
  "Villa Marina Capri Hotel & Spa - Capri, Italy",
  "Villa San Michele - Fiesole, Italy",
  "Villa Sant'Andrea, A Belmond Hotel, Taromina Mare - Taormina, Italy",
  "Vista Palazzo Lago di Como - Como, Italy",
  "Vista Palazzo Verona - Verona, Italy",
  "W Rome - Rome, Italy",
  // Jamaica
  "Half Moon, Jamaica - Montego Bay, Jamaica",
  "Round Hill Hotel & Villas - Montego Bay, Jamaica",
  "S Hotel Montego Bay - Montego Bay, Jamaica",
  // Japan
  "Ace Hotel Kyoto - Kyoto, Japan",
  "Andaz Tokyo Toranomon Hills - Tokyo, Japan",
  "Bellustar Tokyo, a Pan Pacific Hotel - Tokyo, Japan",
  "Bulgari Hotel Tokyo - Tokyo, Japan",
  "Four Seasons Hotel Kyoto - Kyoto, Japan",
  "Four Seasons Hotel Osaka - Osaka, Japan",
  "Four Seasons Hotel Tokyo at Marunouchi - Tokyo, Japan",
  "Four Seasons Hotel Tokyo at Otemachi - Tokyo, Japan",
  "InterContinental Osaka by IHG - Osaka, Japan",
  "IRAPH SUI, a Luxury Collection Hotel, Miyako Okinawa - Miyakojima, Japan",
  "Kimpton Shinjuku Tokyo by IHG - Tokyo, Japan",
  "Palace Hotel Tokyo - Tokyo, Japan",
  "Park Hyatt Niseko Hanazono - Hokkaido, Japan",
  "Shangri-La Tokyo - Tokyo, Japan",
  "Six Senses Kyoto - Kyoto, Japan",
  "Sowaka - Kyoto, Japan",
  "Suiran, A Luxury Collection Hotel, Kyoto - Kyoto, Japan",
  "The Okura Tokyo - Tokyo, Japan",
  "The Peninsula Tokyo - Tokyo, Japan",
  "The Prince Gallery Tokyo Kioicho, A Luxury Collection Hotel - Tokyo, Japan",
  "The Ritz-Carlton, Kyoto - Kyoto, Japan",
  "The Ritz-Carlton, Nikko - Nikko, Japan",
  "The Ritz-Carlton, Osaka - Osaka, Japan",
  "The Ritz-Carlton, Tokyo - Tokyo, Japan",
  "The Strings by InterContinental Tokyo by IHG - Tokyo, Japan",
  "The Tokyo EDITION, Toranomon - Tokyo, Japan",
  "W Osaka - Osaka, Japan",
  // Jordan
  "Four Seasons Hotel Amman - Amman, Jordan",
  // Kuwait
  "Four Seasons Hotel Kuwait at Burj Alshaya - Kuwait City, Kuwait",
  // Macao
  "Four Seasons Hotel Macao - Cotai, Macao",
  "The Grand Suites at Four Seasons - Taipa, Macao",
  // Malaysia
  "Four Seasons Hotel Kuala Lumpur - Kuala Lumpur, Malaysia",
  "Four Seasons Resort Langkawi - Langkawi, Malaysia",
  // Maldives
  "COMO Cocoa Island - South Male Atoll, Maldives",
  "Four Seasons Resort Maldives at Kuda Huraa - Republic of Maldives, Maldives",
  "Four Seasons Resort Maldives at Landaa Giraavaru - Baa Atoll, Maldives",
  "InterContinental Maldives Maamunagau Resort by IHG - Maamunagau Island, Maldives",
  "JOALI Maldives - Male, Maldives",
  "LUX* South Ari Atoll - South Ari Atoll, Maldives",
  "Naladhu Private Island Maldives Resort - Male, Maldives",
  "One&Only Reethi Rah - Reethi Rah, Maldives",
  "Six Senses Kanuhura - Kanuhura, Maldives",
  "Six Senses Laamu - Olhuveli, Maldives",
  "Soneva Fushi - Eydhafushi, Maldives",
  "Taj Exotica Resort & Spa - South Male' Atoll, Maldives",
  // Malta
  "Iniala Harbour House - Valletta, Malta",
  // Mauritius
  "Four Seasons Resort Mauritius at Anahita - Beau Champ, Mauritius",
  "LUX* Grand Baie - Grand Baie, Mauritius",
  "One&Only Le Saint Geran - Mauritius",
  // Mexico
  "Alila Mayakoba - Playa del Carmen, Mexico",
  "Andaz Condesa Mexico City - Mexico City, Mexico",
  "Banyan Tree Mayakoba - Playa del Carmen, Mexico",
  "Banyan Tree Puebla - Puebla, Mexico",
  "Be Tulum Beach & Spa Resort - Tulum, Mexico",
  "Casa de Sierra Nevada, A Belmond Hotel, San Miguel de Allende - San Miguel de Allende, Mexico",
  "Casa Habita, Guadalajara, a Member of Design Hotels - Guadalajara, Mexico",
  "Casa Velas Adults Only All Inclusive - Puerto Vallarta, Mexico",
  "Chablé Maroma - Playa del Carmen, Mexico",
  "Chable Yucatan - Mérida, Mexico",
  "Circulo Mexicano, Mexico, a Member of Design Hotels - Mexico City, Mexico",
  "Condesa df, Mexico City, a Member of Design Hotels - Mexico City, Mexico",
  "Corazon Cabo Resort & Spa - Cabo San Lucas, Mexico",
  "Fairmont Heritage Place, Mayakoba - Solidaridad, Mexico",
  "Four Seasons Hotel Mexico City - Mexico City, Mexico",
  "Four Seasons Resort Los Cabos at Costa Palmas - La Ribera, Mexico",
  "Four Seasons Resort Punta Mita - Punta de Mita, Mexico",
  "Four Seasons Resort Tamarindo - La Manzanilla, Mexico",
  "Grand Velas Boutique Los Cabos - San José del Cabo, Mexico",
  "Grand Velas Los Cabos - All Inclusive - Cabo San Lucas, Mexico",
  "Grand Velas Riviera Maya - All Inclusive - Playa del Carmen, Mexico",
  "Grand Velas Riviera Nayarit - All Inclusive - Nuevo Vallarta, Mexico",
  "Hotel Alexander - Mexico City, Mexico",
  "Hotel Esencia - Solidaridad - Playa del Carmen, Mexico",
  "Hotel San Cristobal - Todos Santos, Mexico",
  "Impression Isla Mujeres by Secrets - Cancun, Mexico",
  "Impression Moxche by Secrets - Playa del Carmen, Mexico",
  "InterContinental Presidente Cozumel Resort & Spa - Cozumel, Mexico",
  "InterContinental Presidente Monterrey by IHG - San Pedro Garza García, Mexico",
  "Kempinski Hotel Cancun - Cancun, Mexico",
  "Kimpton Mas Olas Resort and Spa - El Pescadero, Mexico",
  "Kimpton Virgilio Hotel - Mexico City, Mexico",
  "Maroma, A Belmond Hotel, Riviera Maya - Playa del Carmen, Riviera Maya, Mexico",
  "Mondrian Mexico City Condesa - Mexico City, Mexico",
  "Montage Los Cabos - Cabo San Lucas, Mexico",
  "Naviva, A Four Seasons Resort, Punta Mita, Mexico - Bahia de Banderas, Mexico",
  "NIZUC Resort & Spa - Cancun, Mexico",
  "Nobu Hotel Los Cabos - Cabo San Lucas, Mexico",
  "One&Only Mandarina - Lo de Marcos, Mexico",
  "One&Only Palmilla - San Jose Del Cabo, Mexico",
  "Palmaïa-The House of AïA: All Inclusive Wellness Resort - Playa del Carmen, Mexico",
  "Paradisus La Perla - Playa Del Carmen, Mexico",
  "Paradisus Playa del Carmen - Playa Del Carmen, Mexico",
  "Park Hyatt Los Cabos at Cabo Del Sol - Cabo Del Sol, Mexico",
  "Residences at Zadún, a Ritz-Carlton Reserve - San Jose del Cabo, Mexico",
  "Secrets Akumal - Tulum, Mexico",
  "SLS Cancun - Cancun, Mexico",
  "Sofitel Mexico City Reforma - Mexico City, Mexico",
  "The Cape, a Thompson Hotel - Cabo San Lucas, Mexico",
  "The Ritz-Carlton Residences Mexico City - Mexico City, Mexico",
  "The Ritz-Carlton, Mexico City - Mexico City, Mexico",
  "The Riviera Maya EDITION at Kanai - Solidaridad, Mexico",
  "The St. Regis Kanai Resort, Riviera Maya - Solidaridad, Playa Del Carmen, Mexico",
  "The St. Regis Mexico City - Mexico City, Mexico",
  "The St. Regis Punta Mita Resort - Punta de Mita, Mexico",
  "Thompson Zihuatanejo - Zihuatanejo, Mexico",
  "Unico Hotel Riviera Maya - Adults Only - All Inclusive - Kantenah, Mexico",
  "Viceroy Los Cabos - San Jose del Cabo, Mexico",
  "Viceroy Riviera Maya - Playa del Carmen, Mexico",
  "W Punta de Mita - Punta de Mita, Mexico",
  "Zadún, a Ritz-Carlton Reserve - San Jose del Cabo, Mexico",
  // Monaco
  "Fairmont Monte Carlo - Monaco",
  "Hotel de Paris Monte-Carlo - Monaco",
  "Hotel Hermitage Monte-Carlo - Monaco",
  // Montenegro
  "One&Only Portonovi - Kumbor, Montenegro",
  "The Chedi Lustica Bay - Tivat, Montenegro",
  // Morocco
  "Four Seasons Hotel Casablanca - Casablanca, Morocco",
  "Four Seasons Hotel Rabat at Kasr Al Bahr - Rabat, Morocco",
  "Four Seasons Resort Marrakech - Marrakech, Morocco",
  "Kasbah Tamadot - Asni, Morocco",
  "La Sultana Marrakech - Marrakech, Morocco",
  "Park Hyatt Marrakech - Marrakech, Morocco",
  "Royal Mansour Marrakech - Marrakech, Morocco",
  "The Oberoi, Marrakech - Marrakech, Morocco",
  // Netherlands
  "Anantara Grand Hotel Krasnapolsky Amsterdam - Amsterdam, Netherlands",
  "Andaz Amsterdam, Prinsengracht, by Hyatt - Amsterdam, Netherlands",
  "Conservatorium Hotel - Amsterdam, Netherlands",
  "De L'Europe Amsterdam - Leading Hotels of the World - Amsterdam, Netherlands",
  "InterContinental Amstel Amsterdam by IHG - Amsterdam, Netherlands",
  "Kimpton de Witt Amsterdam - Amsterdam, Netherlands",
  "Pillows Grand Boutique Hotel Maurits at the Park - Amsterdam, Netherlands",
  "Pulitzer Amsterdam - Amsterdam, Netherlands",
  "Sofitel Legend The Grand Amsterdam - Amsterdam, Netherlands",
  "The Dylan Amsterdam - Amsterdam, Netherlands",
  "Tivoli Doelen Amsterdam Hotel - Amsterdam, Netherlands",
  // New Zealand
  "Blanket Bay - Glenorchy, New Zealand",
  "Cordis, Auckland - Auckland, New Zealand",
  "InterContinental Auckland - Auckland, New Zealand",
  "Park Hyatt Auckland - Auckland, New Zealand",
  // Norway
  "Sommerro - Oslo, Norway",
  // Panama
  "The Santa Maria, a Luxury Collection Hotel & Golf Resort, Panama City - Panamá, Panama",
  // Peru
  "Miraflores Park, A Belmond Hotel, Lima - Lima, Peru",
  "Monasterio, A Belmond Hotel, Cusco - Cusco, Peru",
  "Palacio Nazarenas, A Belmond Hotel, Cusco - Cusco, Peru",
  // Philippines
  "Raffles Makati - Makati, Philippines",
  "Shangri-La Boracay - Boracay Island, Philippines",
  "Shangri-La The Fort, Manila - Taguig City, Philippines",
  // Poland
  "Nobu Hotel Warsaw - Warsaw, Poland",
  "Raffles Europejski Warsaw - Warszawa, Poland",
  // Portugal
  "BELA VISTA Hotel & SPA - Praia da Rocha, Portugal",
  "Convent Square Lisbon, Vignette Collection by IHG - Lisbon, Portugal",
  "Corinthia Lisbon - Lisbon, Portugal",
  "Four Seasons Hotel Ritz Lisbon - Lisbon, Portugal",
  "Herdade da Malhadinha Nova - Albernoa-Beja, Portugal",
  "InterContinental Lisbon by IHG - Lisbon, Portugal",
  "InterContinental Porto-Palacio das Cardosas - Porto, Portugal",
  "Kimpton Atlântico Algarve by IHG - Albufeira, Portugal",
  "L'And Vineyards - Montemor-O-Novo, Portugal",
  "Octant Douro - Castelo de Paiva, , Portugal",
  "Octant Furnas - Furnas, Portugal",
  "Octant Ponta Delgada - Ponta Delgada, Portugal",
  "Octant Praia Verde - Castro Marim, Portugal",
  "Octant Vila Monte - Olhão, Portugal",
  "Pine Cliffs Ocean Suites, a Luxury Collection Resort & Spa - Albufeira, Portugal",
  "Reids Palace, A Belmond Hotel, Madeira - Funchal, Portugal",
  "Savoy Palace - Funchal, Portugal",
  "Six Senses Douro Valley - Samodães, Lamego, Portugal",
  "The One Palacio da Anunciada - Lisboa, Portugal",
  "Tivoli Avenida Liberdade Lisboa – A Leading hotel of the world - Lisbon, Portugal",
  "Valverde Lisboa Hotel & Garden - Lisbon, Portugal",
  "Vermelho Melides - Relais & Châteaux - Grandola, Portugal",
  "Viceroy at Ombria Algarve - Loulé, Portugal",
  "W Algarve - Albufeira, Portugal",
  "W Residences Algarve - Albufeira, Portugal",
  // Puerto Rico
  "Condado Vanderbilt Hotel - San Juan, Puerto Rico",
  "Dorado Beach, a Ritz-Carlton Reserve - Dorado, Puerto Rico",
  "Residences at Dorado Beach, a Ritz-Carlton Reserve - Dorado, Puerto Rico",
  "The St. Regis Bahia Beach Resort, Puerto Rico - Rio Grande, Puerto Rico",
  // Qatar
  "Four Seasons Hotel Doha - Doha, Qatar",
  "Four Seasons Resort And Residences At The Pearl - Qatar - Doha, Qatar",
  // Rwanda
  "One&Only Nyungwe House - Gisakura Nyamasheke, Rwanda",
  // Saudi Arabia
  "Four Seasons Hotel Riyadh - Riyadh, Saudi Arabia",
  "The St. Regis Red Sea Resort - Red Sea, Saudi Arabia",
  // Seychelles
  "Four Seasons Resort Seychelles - Mahé Island, Seychelles",
  "Four Seasons Resort Seychelles at Desroches Island - Desroches Island, Seychelles",
  "Six Senses Zil Pasyon Seychelles - Felicite Island, Seychelles",
  // Singapore
  "Andaz Singapore - Singapore",
  "Capella Singapore - Sentosa Island, Singapore 098297, Singapore",
  "COMO Metropolitan Singapore - Singapore",
  "Four Seasons Hotel Singapore - Singapore",
  "InterContinental Singapore Robertson Quay by IHG - Singapore",
  "JW Marriott Hotel Singapore South Beach - Singapore",
  "Mondrian Singapore Duxton - Singapore",
  "Pan Pacific Orchard - Singapore",
  "Pan Pacific Singapore - Singapore",
  "Raffles Singapore - Singapore",
  "The Fullerton Bay Hotel Singapore - Singapore",
  // South Africa
  "Cape Grace, A Fairmont Managed Hotel - Cape Town, South Africa",
  "Ellerman House - Cape Town, South Africa",
  "Four Seasons Hotel The Westcliff, Johannesburg - Randburg, South Africa",
  "Mount Nelson, A Belmond Hotel, Cape Town - Cape Town, South Africa",
  "One&Only Cape Town - Cape Town, South Africa",
  "The Twelve Apostles Hotel and Spa - Cape Town, South Africa",
  // South Korea
  "Four Seasons Hotel Seoul - Seoul, South Korea",
  "InterContinental Grand Seoul Parnas - Gangnam-gu, South Korea",
  "Mondrian Seoul Itaewon - Seoul, South Korea",
  "Park Hyatt Seoul - seoul, South Korea",
  "The Shilla Seoul - Seoul, South Korea",
  // St. Martin
  "La Samanna, A Belmond Hotel, St. Martin - St Martin, St. Martin",
  // Sweden
  "At Six - Stockholm, Sweden",
  "Grand Hôtel Stockholm - Stockholm, Sweden",
  "Nobis Hotel Stockholm - Stockholm, Sweden",
  // Switzerland
  "Alex Lake Zürich - Thalwil (Zurich), Switzerland",
  "Carlton Hotel St. Moritz - St. Moritz, Switzerland",
  "Crans Ambassador - Crans-Montana, Switzerland",
  "Four Seasons Hotel des Bergues Geneva - Geneva, Switzerland",
  "Grand Hotel Des Bains Kempinski St. Moritz - St Moritz, Switzerland",
  "Hotel d'Angleterre Geneva - Geneva, Switzerland",
  "Hotel Eden Roc - Ascona, Switzerland",
  "Kempinski Palace Engelberg - Engelberg, Switzerland",
  "La Réserve Eden au Lac Zurich - Zürich, Switzerland",
  "La Reserve Geneve - Hotel & Spa - Geneva, Switzerland",
  "Mont Cervin Palace - Zermatt, Switzerland",
  "Radisson Blu Hotel Reussen Andermatt - Andermatt, Switzerland",
  "Six Senses Crans-Montana - Crans-Montana, Switzerland",
  "The Alpina Gstaad - Gstaad, Switzerland",
  "The Dolder Grand - Zurich, Switzerland",
  "The Ritz-Carlton Hotel de la Paix, Geneva - Geneva, Switzerland",
  "The View Lugano - Paradiso, Switzerland",
  "Tschuggen Grand Hotel - Arosa, Switzerland",
  "W Verbier - Verbier, Switzerland",
  "Widder Hotel - Zurich, Switzerland",
  // Taiwan
  "Hotel Proverbs Taipei - Taipei City, Taiwan",
  // Thailand
  "Anantara Chiang Mai Resort - Chiang Mai, Thailand",
  "Anantara Rasananda Koh Phangan Villas - Suratthani, Thailand",
  "Andaz Pattaya Jomtien Beach - Chonburi, Thailand",
  "Banyan Tree Krabi - Krabi, Thailand",
  "Banyan Tree Phuket - Choeng Thale, Thailand",
  "Banyan Tree Samui - Koh Samui, Thailand",
  "Capella Bangkok - Bangkok, Thailand",
  "Devasom Khao Lak Beach Resort & Villas - Phang Nga, Thailand",
  "Dinso Resort & Villas Phuket, Vignette Collection by IHG - Patong, Thailand",
  "Four Seasons Hotel Bangkok at Chao Phraya River - Bangkok, Thailand",
  "Four Seasons Resort Chiang Mai - Mae Rim, Thailand",
  "Four Seasons Resort Koh Samui - Koh Samui, Thailand",
  "Four Seasons Tented Camp Golden Triangle - Chiang Saen, Thailand",
  "Iniala Beach House - Takua Thung, Thailand",
  "InterContinental Pattaya Resort by IHG - Pattaya, Thailand",
  "InterContinental Phuket Resort by IHG - Kamala, Thailand",
  "Keemala - Phuket, Thailand",
  "Kimpton Kitalay Samui by IHG - Koh Samui, Thailand",
  "Kimpton Maa-Lai Bangkok by IHG - Bangkok, Thailand",
  "Napasai, A Belmond Hotel, Koh Samui - Koh Samui, Thailand",
  "Phulay Bay, a Ritz-Carlton Reserve - Krabi, Thailand",
  "Sindhorn Kempinski Hotel Bangkok - Bangkok, Thailand",
  "The Naka Island, a Luxury Collection Resort & Spa, Phuket - Pa Klok, Thailand",
  "The Ritz-Carlton, Bangkok - Bangkok, Thailand",
  "The Ritz-Carlton, Koh Samui - Koh Samui, Thailand",
  "The Siam - Bangkok, Thailand",
  "The St. Regis Bangkok - Bangkok, Thailand",
  "The Standard, Bangkok Mahanakhon - Bangkok, Thailand",
  // Tunisia
  "Four Seasons Hotel Tunis - Tunis, Tunisia",
  // Turkey
  "Ariana Sustainable Luxury Lodge - Special Class - Nevsehir, Türkiye",
  "Four Seasons Hotel Istanbul at the Bosphorus - Istanbul, Türkiye",
  "Kempinski Hotel Barbaros Bay Bodrum - Mugla, Türkiye",
  "Raffles Istanbul - Istanbul, Türkiye",
  "Six Senses Kaplankaya - Milas, Türkiye",
  "The Bank Hotel Istanbul - Istanbul, Türkiye",
  "The Peninsula Istanbul - Istanbul, Türkiye",
  "The Ritz-Carlton, Istanbul - Istanbul, Türkiye",
  // Turks & Caicos Islands
  "Beach Enclave - Providenciales, Turks & Caicos Islands",
  "COMO Parrot Cay - Parrot Cay, Turks & Caicos Islands",
  "Grace Bay Club - Providenciales, Turks & Caicos Islands",
  "Rock House - Providenciales, Turks & Caicos Islands",
  "Salterra, a Luxury Collection Resort & Spa, South Caicos - Cockburn Harbour, Turks & Caicos Islands",
  "The Ritz-Carlton, Turks & Caicos - Providenciales, Turks & Caicos Islands",
  "Wymara Resort and Villas - Providenciales, Turks & Caicos Islands",
  // U.S. Virgin Islands
  "Buoy Haus Beach Resort St. Thomas, Autograph Collection - St. Thomas, U.S. Virgin Islands",
  "The Ritz-Carlton, St. Thomas - St. Thomas, U.S. Virgin Islands",
  // United Arab Emirates
  "Atlantis The Royal - Dubai, United Arab Emirates",
  "Bulgari Resort Dubai - Dubai, United Arab Emirates",
  "Burj Al Arab Jumeirah - Dubai, United Arab Emirates",
  "Four Seasons Hotel Abu Dhabi at Al Maryah Island - Abu Dhabi, United Arab Emirates",
  "Four Seasons Hotel Dubai International Financial Centre - Dubai, United Arab Emirates",
  "Four Seasons Resort Dubai at Jumeirah Beach - Dubai, United Arab Emirates",
  "InterContinental Residences Dubai Business Bay by IHG - Dubai, United Arab Emirates",
  "Jumeirah Al Naseem Dubai - Dubai, United Arab Emirates",
  "Jumeirah Dar Al Masyaf - Dubai, United Arab Emirates",
  "Jumeirah Marsa Al Arab - Dubai, United Arab Emirates",
  "One&Only The Palm - Dubai, United Arab Emirates",
  "SLS Dubai Hotel & Residences - Dubai, United Arab Emirates",
  "SO/ Uptown Dubai - Dubai, United Arab Emirates",
  "Taj Dubai - Dubai, United Arab Emirates",
  "The Lana - Dorchester Collection - Dubai, United Arab Emirates",
  "The Ritz-Carlton, Dubai - Dubai, United Arab Emirates",
  // United Kingdom
  "1 Hotel Mayfair - London, United Kingdom",
  "100 Princes Street - Edinburgh, United Kingdom",
  "11 Cadogan Gardens and The Apartments - London, United Kingdom",
  "45 Park Lane - Dorchester Collection - London, United Kingdom",
  "Brown's Hotel, a Rocco Forte hotel - London, United Kingdom",
  "Bulgari Hotel London - London, United Kingdom",
  "Claridge's - London, United Kingdom",
  "Cliveden House - an Iconic Luxury Hotel - Maidenhead, United Kingdom",
  "COMO Metropolitan London - London, United Kingdom",
  "Corinthia London - London, United Kingdom",
  "Coworth Park - Dorchester Collection - Ascot, United Kingdom",
  "Dorset Square Hotel, Firmdale Hotels - London, United Kingdom",
  "Estelle Manor - Park, United Kingdom",
  "Fairmont Windsor Park - Egham, United Kingdom",
  "Four Seasons Hotel Hampshire - Hook, United Kingdom",
  "Four Seasons Hotel London at Park Lane - London, United Kingdom",
  "Four Seasons Hotel London at Tower Bridge - London, United Kingdom",
  "Glenapp Castle - Girvan, United Kingdom",
  "Grosvenor House Suites - London, United Kingdom",
  "Haymarket Hotel - London, United Kingdom",
  "Hotel Cafe Royal - London, United Kingdom",
  "InterContinental Edinburgh The George by IHG - Edinburgh, United Kingdom",
  "InterContinental London Park Lane by IHG - London, United Kingdom",
  "Kimpton Blythswood Square Hotel - Glasgow, United Kingdom",
  "Kimpton Charlotte Square by IHG - Edinburgh, United Kingdom",
  "Kimpton Fitzroy London by IHG - London, United Kingdom",
  "Le Manoir aux Quat'Saisons, A Belmond Hotel, Oxfordshire - Oxford, United Kingdom",
  "One Aldwych - London, United Kingdom",
  "Park Hyatt London River Thames - London, United Kingdom",
  "Raffles London at The OWO - London, United Kingdom",
  "Shangri-La The Shard, London - London, United Kingdom",
  "St Martins Lane London - London, United Kingdom",
  "The Balmoral Hotel - Edinburgh, United Kingdom",
  "The Berkeley - London, United Kingdom",
  "The Cadogan, A Belmond Hotel, London - London, United Kingdom",
  "The Connaught - Mayfair, United Kingdom",
  "The Dorchester - London, United Kingdom",
  "The Emory - Belgravia, United Kingdom",
  "The Gleneagles Hotel - Perthshire, United Kingdom",
  "The Gleneagles Townhouse - Edinburgh, United Kingdom",
  "The Lanesborough, Oetker Hotels - London, United Kingdom",
  "The Langham, London - London, United Kingdom",
  "The Langley, a Luxury Collection Hotel, Buckinghamshire - Slough, United Kingdom",
  "The London EDITION - London, United Kingdom",
  "The Londoner Hotel - London, United Kingdom",
  "The Marylebone - London, United Kingdom",
  "The Milestone Hotel & Residences - London, United Kingdom",
  "The Ned - London, United Kingdom",
  "The Peninsula London - London, United Kingdom",
  "The Royal Crescent Hotel & Spa - Bath, United Kingdom",
  "The Savoy, A Fairmont Managed Hotel - London, United Kingdom",
  "The Soho Hotel - London, United Kingdom",
  "The Standard, London - London, United Kingdom",
  "Virgin Hotels Edinburgh - Edinburgh, United Kingdom",
  "W Edinburgh - Edinburgh, United Kingdom",
  // United States (partial list - continuing in next chunk)
  "1 Hotel Brooklyn Bridge - Brooklyn, New York",
  "1 Hotel Hanalei Bay - Princeville, Hawaii",
  "1 Hotel Nashville - Nashville, Tennessee",
  "1 Hotel San Francisco - San Francisco, California",
  "1 Hotel South Beach - Miami Beach, Florida",
  "1 Hotel West Hollywood - West Hollywood, California",
  "1 21C Museum Hotel Cincinnati - Cincinnati, Ohio",
  "21c Museum Hotel Louisville - Louisville, Kentucky",
  "21c Museum Hotel St Louis - St. Louis, Missouri",
  "27 North - Healdsburg, California",
  "33 Seaport Hotel New York - New York",
  "Ace Hotel Brooklyn - Brooklyn, New York",
  "Acqualina Resort & Residences - Sunny Isles, Florida",
  "Alila Marea Beach Resort, a Hyatt Luxury Resort - Encinitas, California",
  "Alila Napa Valley, a Hyatt Luxury Resort - St Helena, California",
  "Alila Ventana Big Sur, a Hyatt Luxury Resort - Big Sur, California",
  "Alma San Diego Downtown, a Tribute Portfolio Hotel - San Diego, California",
  "Amara Resort and Spa - Sedona, Arizona",
  "Ambiente A Landscape Hotel, Sedona - Sedona, Arizona",
  "Amrit Ocean Resort - Singer Island, Florida",
  "Andaz Maui at Wailea Resort - Wailea, Hawaii",
  "Andaz Miami Beach - Miami Beach, Florida",
  "Andaz Scottsdale Resort & Bungalows - Scottsdale, Arizona",
  "ARIA Resort & Casino - Las Vegas, Nevada",
  "ARIA Sky Suites - Las Vegas, Nevada",
  "Asbury Ocean Club Hotel - Asbury Park, New Jersey",
  "Auberge Du Soleil - St. Helena, California",
  "Austin Proper Hotel, a Member of Design Hotels - Austin, Texas",
  "Avalon Hotel & Bungalows Palm Springs - Palm Springs, California",
  "Baccarat Hotel New York - New York",
  "Bardessono Hotel and Spa - Yountville, California",
  "Beach Club at The Boca Raton - Boca Raton, Florida",
  "Beach Plum Farm Cottages - West Cape May, New Jersey",
  "Bellagio Hotel and Casino - Las Vegas, Nevada",
  "Beverly Wilshire - Beverly Hills, A Four Seasons Hotel - Beverly Hills, California",
  "Black Desert Resort - Ivins, Utah",
  "Black Rock Mountain Resort - Heber City, Utah",
  "Black Walnut Inn & Vineyard - Dundee, Oregon",
  "Boston Harbor Hotel - Boston, Massachusetts",
  "Brenton Hotel - Newport, Rhode Island",
  "Brush Creek Ranch - Saratoga, Wyoming",
  "C.Baldwin Hotel a Hilton Curio Collection - Houston, Texas",
  "Caesars Republic Scottsdale, A Hilton Hotel - Scottsdale, Arizona",
  "Camp Creek Inn - Panama City Beach, Florida",
  "Canoe Place Inn & Cottages - Hampton Bays, New York",
  "Canyon Ranch Lenox - Lenox, Massachusetts",
  "Canyon Ranch Tucson - Tucson, Arizona",
  "Canyon Ranch Woodside - Woodside, California",
  "Carmel Valley Ranch - Carmel, California",
  "Carneros Resort and Spa - Napa, California",
  "Casa Cipriani New York - New York",
  "Castle Hill Inn - Newport, Rhode Island",
  "Castle Hot Springs - Morristown, Arizona",
  "Cavallo Point - Sausalito, California",
  "Chatham Bars Inn - Chatham, Massachusetts",
  "Chicago Athletic Association, a Hyatt Hotel - Chicago, Illinois",
  "Cloister at The Boca Raton - Boca Raton, Florida",
  "Colony Palms Hotel & Bungalows - Palm Springs, California",
  "CordeValle - San Martin, California",
  "Dawn Ranch - Guerneville, California",
  "Downtown L.A. Proper - Los Angeles, California",
  "Dunton Hot Springs - Dolores, Colorado",
  "Eaton DC - Washington, District of Columbia",
  "Eau Palm Beach Resort & Spa - Manalapan, Florida",
  "Eden Roc Miami Beach - Miami Beach, Florida",
  "Edgewood Tahoe Resort - Stateline, Nevada",
  "EHP Resort & Marina - East Hampton, New York",
  "El Encanto Santa Barbara - Santa Barbara, California",
  "Elliot Park Hotel, Autograph Collection - Minneapolis, Minnesota",
  "Emeline - Charleston, South Carolina",
  "Enchantment Resort - Sedona, Arizona",
  "Equinox Hotel New York - New York",
  "Espacio The Jewel Of Waikiki - Honolulu, Hawaii",
  "Estancia La Jolla Hotel & Spa - La Jolla, California",
  "Faena Hotel Miami Beach - Miami Beach, Florida",
  "Fairmont Austin - Austin, Texas",
  "Fairmont Chicago, Millennium Park - Chicago, Illinois",
  "Fairmont Copley Plaza, Boston - Boston, Massachusetts",
  "Fairmont Dallas - Dallas, Texas",
  "Fairmont El San Juan Hotel - Carolina, Puerto Rico",
  "Fairmont Grand Del Mar - San Diego, California",
  "Fairmont Kea Lani - Wailea, Hawaii",
  "Fairmont Miramar Hotel - Santa Monica, California",
  "Fairmont Olympic Hotel - Seattle, Washington",
  "Fairmont Orchid, Hawaii - Kohala Coast, Hawaii",
  "Fairmont San Francisco - San Francisco, California",
  "Fairmont Scottsdale Princess - Scottsdale, Arizona",
  "Fairmont Sonoma Mission Inn & Spa - Sonoma, California",
  "Farmhouse Inn - Forestville, California",
  "Fontainebleau Las Vegas - Las Vegas, Nevada",
  "Fontainebleau Miami Beach - Miami Beach, Florida",
  "FORTH Hotel Atlanta - Atlanta, Georgia",
  "Fouquet's New York - New York",
  "Four Seasons Hotel and Residences Fort Lauderdale - Fort Lauderdale, Florida",
  "Four Seasons Hotel at The Surf Club - Surfside, Florida",
  "Four Seasons Hotel Atlanta - Atlanta, Georgia",
  "Four Seasons Hotel Austin - Austin, Texas",
  "Four Seasons Hotel Baltimore - Baltimore, Maryland",
  "Four Seasons Hotel Boston - Boston, Massachusetts",
  "Four Seasons Hotel Chicago - Chicago, Illinois",
  "Four Seasons Hotel Denver - Denver, Colorado",
  "Four Seasons Hotel Houston - Houston, Texas",
  "Four Seasons Hotel Las Vegas - Las Vegas, Nevada",
  "Four Seasons Hotel Los Angeles at Beverly Hills - Los Angeles, California",
  "Four Seasons Hotel Los Angeles at Westlake Village - Thousand Oaks, California",
  "Four Seasons Hotel Miami - Miami, Florida",
  "Four Seasons Hotel Minneapolis - Minneapolis, Minnesota",
  "Four Seasons Hotel New Orleans - New Orleans, Louisiana",
  "Four Seasons Hotel New York - New York",
  "Four Seasons Hotel New York Downtown - New York",
  "Four Seasons Hotel One Dalton Street, Boston - Boston, Massachusetts",
  "Four Seasons Hotel Philadelphia at Comcast Center - Philadelphia, Pennsylvania",
  "Four Seasons Hotel San Francisco - San Francisco, California",
  "Four Seasons Hotel San Francisco at Embarcadero - San Francisco, California",
  "Four Seasons Hotel Seattle - Seattle, Washington",
  "Four Seasons Hotel Silicon Valley at East Palo Alto - Palo Alto, California",
  "Four Seasons Hotel St Louis - St. Louis, Missouri",
  "Four Seasons Hotel Washington DC - Washington, District of Columbia",
  "Four Seasons Nashville - Nashville, Tennessee",
  "Four Seasons Resort and Residences Napa Valley - Calistoga, California",
  "Four Seasons Resort Hualalai - Kailua-Kona, Hawaii",
  "Four Seasons Resort Jackson Hole - Teton Village, Wyoming",
  "Four Seasons Resort Lanai - Lanai City, Hawaii",
  "Four Seasons Resort Maui at Wailea - Kihei, Hawaii",
  "Four Seasons Resort Oahu at Ko Olina - Kapolei, Hawaii",
  "Four Seasons Resort Orlando at WALT DISNEY WORLD® Resort - Lake Buena Vista, Florida",
  "Four Seasons Resort Palm Beach - Palm Beach, Florida",
  "Four Seasons Resort Rancho Encantado Santa Fe - Santa Fe, New Mexico",
  "Four Seasons Resort Scottsdale at Troon North - Scottsdale, Arizona",
  "Four Seasons Resort Vail - Vail, Colorado",
];

// This is a simplified version - the full script would include all ~1300 hotels
// For now, let's create the structure with the hotels we have

function parseHotelEntry(entry: string): Partial<Hotel> {
  // Format: "Hotel Name - City, Country" or "Hotel Name - City, State, Country"
  const parts = entry.split(' - ');
  const name = parts[0].trim();
  const locationPart = parts.slice(1).join(' - ').trim();

  // Parse location
  const locationParts = locationPart.split(', ').map(p => p.trim());
  let city = '';
  let region: string | undefined;
  let country = '';

  if (locationParts.length >= 2) {
    country = locationParts[locationParts.length - 1];
    city = locationParts[0];
    if (locationParts.length > 2) {
      region = locationParts.slice(1, -1).join(', ');
    }
  } else if (locationParts.length === 1) {
    // Just country (e.g., "Monaco", "Singapore")
    country = locationParts[0];
    city = locationParts[0];
  }

  // Extract brand from name if present
  let brand: string | undefined;
  const brandPatterns = [
    'Four Seasons', 'Ritz-Carlton', 'St. Regis', 'Fairmont', 'Sofitel',
    'InterContinental', 'W ', 'Kimpton', 'Andaz', 'Park Hyatt', 'Grand Hyatt',
    'Hyatt Regency', 'JW Marriott', 'Shangri-La', 'Mandarin Oriental',
    'Peninsula', 'Belmond', 'Rosewood', 'One&Only', 'Six Senses', 'Bulgari',
    'COMO', 'Raffles', 'Langham', 'Montage', 'Pendry', 'Thompson', 'Nobu'
  ];

  for (const pattern of brandPatterns) {
    if (name.includes(pattern)) {
      brand = pattern.replace('W ', 'W Hotels');
      break;
    }
  }

  return {
    id: uuidv4(),
    name,
    brand,
    city,
    region,
    country,
    needs_review: false
  };
}

async function main() {
  console.log('Building hotel dataset...');
  console.log(`Processing ${rawHotels.length} hotels...`);

  const hotels: Hotel[] = rawHotels.map(entry => {
    const parsed = parseHotelEntry(entry);
    return {
      id: parsed.id!,
      name: parsed.name!,
      brand: parsed.brand,
      city: parsed.city!,
      region: parsed.region,
      country: parsed.country!,
      needs_review: true, // All need geocoding
    };
  });

  const dataset: HotelDataset = {
    meta: {
      data_version: 'v1',
      last_built_at: new Date().toISOString(),
      source_url: 'https://www.awardtravel.co/blog/the-edit-by-chase-list'
    },
    hotels
  };

  // Write the initial dataset
  const outputPath = './data/edit_hotels.json';
  writeFileSync(outputPath, JSON.stringify(dataset, null, 2));
  console.log(`Wrote ${hotels.length} hotels to ${outputPath}`);
  console.log('Note: Hotels need geocoding. Run the enrichment script next.');
}

main().catch(console.error);
